### ISSUE TITLE
Use Timo's research as mantik showcase

### ISSUE THREAD

**Issue by thomose** [mantik-ai/tutorials#7]
## Problem to solve

As mantik user I want to have a gallery of projects showcasing the platform, so that I can get an immediate idea of the platform's capabilities.

## Details

This story is only workable iff permission was granted in #5.

## Proposal

 - [x] Collect code dependencies in a `requirements.txt` file
 - [x] Create Dockerfile or apptainer recipe to install the project into a container
 - [x] Write entrypoint scripts and the corresponding `mlproject` file
 - [x] Include mlflow tracking to mantik into the scripts
 - [x] Create an experiment on `cloud.mantik.ai`
 - [x] Run the project on JUWELS and track to `cloud.mantik.ai`
 - [x] Write a README with a project description and citations of papers etc.

## Acceptance

 - [x] Project can be built and run
 - [x] Results are tracked to mantik
 - [x] README contains links to publications, original repo (if possible) and explicitly names Timo as original author of the code

**Comment by Angie25** [comment]
- Project's code is available in gitlab and public.
- The code with the tracking enabled is ready, but needs to be tested in Juwels. It was not possible to run the code in the local machine, since there are no GPUs.

**Comment by Angie25** [comment]
README sample

Integrating models from the paper with the topic Exploring Wilderness Using Explainable Machine Learning in Satellite Imagery into the AI platform. 
This paper exploits the application of a novel explainable machine learning technique to satellite images which show wild and anthropogenic areas in Fennoscandia. Occluding certain activations in an interpretable artificial neural network the authors complete a comprehensive sensitivity analysis regarding wild and anthropogenic characteristics. The approach advances explainable machine learning for remote sensing, offers opportunities for comprehensive analyses of existing wilderness, and has practical relevance for conservation efforts. 

Through the AI-platform it is possible to manage and track various experiments. In order to run the models, we have constructed a singularity container which consists of all the necessary packages to run the project. The container provides flexibility for running the code in different platforms such as Juwels. Additionally, the model parameters can be logged explicitly in the training code. Thus, the code can run using the HPC resources and at the same time its metrics can be tracked from the mantik platform.


Related papers: **"Exploring Wilderness Using Explainable Machine Learning in Satellite Imagery" (2022) by Timo T. Stomberg, Taylor Stone, Johannes Leonhardt, Immanuel Weber, and Ribana Roscher; https://doi.org/10.48550/arXiv.2203.00379**

Gitlab link: https://gitlab.jsc.fz-juelich.de/kiste/asos/-/tree/main/

**Comment by markusabel** [comment]
Pretty good, I think.
Hope that we can use it soon


--


Priv. Doz. Dr. Markus Abel,
CEO

Ambrosys GmbH - Gesellschaft für Management komplexer Systeme

Reiterweg 3
14469 Potsdam
Phone: +4933127319540
Fax: +4933127319542

Registergericht: Amtsgericht Potsdam, HRB 21228 P
Geschäftsführer: Dr. Markus Abel, Dr. Markus Quade
